# Generated by Django 4.1.5 on 2023-02-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='relationship',
            field=models.CharField(choices=[('P', 'Padre'), ('M', 'Madre'), ('E', 'Esposa'), ('H', 'Hijo'), ('A', 'Amigo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('P', 'Separado'), ('D', 'Divorciado'), ('V', 'Viudo')], max_length=10),
        ),
    ]
