# Generated by Django 4.1.5 on 2023-02-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_beneficiary_relationship_alter_beneficiary_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='birthday',
            field=models.DateTimeField(auto_now_add=True, verbose_name='birthday'),
        ),
    ]
